version: '3.8'

services:

  app_database:
    image: postgres:14.4-alpine
    container_name: app-database
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=app_db
    ports:
      - '5432:5432'
    volumes:
      - app_database:/var/lib/postgresql/data

  search_database:
    {% if cookiecutter.search_backend == "elasticsearch" -%}
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    {% elif cookiecutter.search_backend == "opensearch" -%}
    image: opensearchproject/opensearch:2.1.0{% endif  %}
    container_name: search-database
    environment:
      - node.name=search_database
      - discovery.type=single-node
      {% if cookiecutter.search_backend == "elasticsearch" -%}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      {% elif cookiecutter.search_backend == "opensearch" -%}
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"{% endif %}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search_database:/usr/share/{{ cookiecutter.search_backend }}/data
    ports:
      - '9200:9200'
      {% if cookiecutter.search_backend == "opensearch" -%}
      - '9600:9600' # required for Performance Analyzer{% endif %}

  {{ cookiecutter.project_slug|replace('-', '_') }}_development:
    image: {{ cookiecutter.project_slug }}-development
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    container_name: {{ cookiecutter.project_slug }}-development
    profiles:
      - development
    env_file: docker-compose.env
    volumes:
      - ../.:/home/app
    ports:
      - '{{ cookiecutter.default_local_port }}:{{ cookiecutter.default_local_port }}'
    depends_on:
      - app_database
      - search_database

  {{ cookiecutter.project_slug|replace('-', '_') }}_production:
    image: {{ cookiecutter.project_slug }}-production
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: {{ cookiecutter.project_slug }}-production
    profiles:
      - production
    env_file: docker-compose.env
    ports:
      - '{{ cookiecutter.default_docker_port }}:{{ cookiecutter.default_docker_port }}'
    depends_on:
      - app_database
      - search_database

volumes:
  app_database:
    driver: local
  search_database:
    driver: local
