name: Push CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.1.13"]
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cookiecutter, poetry
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter poetry
      - name: Create search project
        run: |
          git config --global init.defaultBranch main
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cookiecutter --no-input --output-dir /tmp .
          cd /tmp/search-project
      - name: Build docker images
        run: |
          pwd
          cd /tmp/search-project
          ./scripts/build.sh
      - name: Run app_database, search_database services
        run: docker compose -f docker/docker-compose.yml up --build
      - name: Run linters via pre-commit
        run: docker compose -f docker/docker-compose.yml run --deamon --rm search_project_development ./scripts/lint.sh
      - name: Run tests and coverage
        run: docker compose -f docker/docker-compose.yml run --deamon --rm search_project_development ./scripts/test.sh
